modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0"

[[mods]]
modId="mchjong"
version="${version}"
displayName="MChjong"
logoFile="assets/mchjong/icon.png"
authors="SkyEye_FAST"
description='''Playable, in-world mahjong tables with configurable rules.'''

[[dependencies.mchjong]]
modId="forge"
mandatory=true
versionRange="[${forge_loader_min_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.mchjong]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.mchjong]]
modId="jei"
mandatory=false
versionRange="[${jei_version},16)"
ordering="AFTER"
side="CLIENT"

[[dependencies.mchjong]]
modId="emi"
mandatory=false
versionRange="[${emi_version},2)"
ordering="AFTER"
side="CLIENT"
