modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0"

[[mods]]
modId="mchjong"
version="${version}"
displayName="MChjong"
logoFile="assets/mchjong/icon.png"
authors="SkyEye_FAST"
description='''Playable, in-world mahjong tables with configurable rules.'''

[[dependencies.mchjong]]
modId="ponder"
mandatory=false
versionRange="[${create_ponder_min_version},2)"
ordering="AFTER"
side="CLIENT"

[[dependencies.mchjong]]
modId="patchouli"
mandatory=false
versionRange="[${patchouli_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.mchjong]]
modId="create"
mandatory=false
versionRange="[${create_min_version},7)"
ordering="AFTER"
side="BOTH"

[[dependencies.mchjong]]
modId="touhou_little_maid"
mandatory=false
versionRange="[${touhou_little_maid_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.mchjong]]
modId="forge"
mandatory=true
versionRange="[${forge_loader_min_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.mchjong]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.mchjong]]
modId="jei"
mandatory=false
versionRange="[${jei_version},16)"
ordering="AFTER"
side="CLIENT"

[[dependencies.mchjong]]
modId="emi"
mandatory=false
versionRange="[${emi_version},2)"
ordering="AFTER"
side="CLIENT"

[[dependencies.mchjong]]
modId="roughlyenoughitems"
mandatory=false
versionRange="[${rei_version},13)"
ordering="AFTER"
side="CLIENT"
