# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Minecraft/Fabric build profile
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
java_version=21
minecraft_java_version=17
loader_version=0.19.5
fabric_loader_min_version=0.16.10
loom_version=1.17.21

# Mod Properties
mod_version=0.8.1-SNAPSHOT
maven_group=top.skyeyefast.mchjong

# Dependencies
fabric_version=0.92.12+1.20.1
mahjong_utils_version=0.7.7
kotlin_version=2.3.20
kotlinx_serialization_version=1.9.0
shadow_version=9.6.1
junit_version=5.11.4
gson_version=2.10.1
night_config_version=3.8.3
patchouli_version=1.20.1-85
ponder_version=1.0.92
flywheel_version=1.0.5
create_forge_version=6.0.8-289
create_fabric_version=6.0.8.1+build.1744-mc1.20.1
registrate_version=MC1.20-1.3.3
mixin_extras_version=0.4.1
create_min_version=6.0.8
create_ponder_min_version=1.0.91
jei_version=15.59.0.212
emi_version=1.1.24+1.20.1
rei_version=12.0.684
cloth_config_version=11.0.99
architectury_version=9.0.7
touhou_little_maid_version=1.5.3-forge+mc1.20.1
orihime_version=0.8.2-forge1.5.3+mc1.20.1
forge_config_api_port_version=8.0.3
cardinal_components_version=5.2.3
porting_lib_version=2.3.8+1.20.1
reach_entity_attributes_version=2.4.0
nashorn_version=15.4
spotless_version=8.10.2

# Legacy Forge build tooling
moddev_version=2.0.147

# Forge profile
forge_version=47.4.23
forge_loader_min_version=47.4.23
