pluginManagement {
	repositories {
		maven {
			name = 'AliyunGradlePlugin'
			url = 'https://maven.aliyun.com/repository/gradle-plugin/'
		}
		maven {
			name = 'AliyunPublic'
			url = 'https://maven.aliyun.com/repository/public/'
		}
		maven {
			name = 'BMCLAPI'
			url = 'https://bmclapi2.bangbang93.com/maven/'
		}
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'mchjong'
include 'engine', 'neoforge', 'art'
