pluginManagement {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		maven {
			name = 'AliyunGradlePlugin'
			url = 'https://maven.aliyun.com/repository/gradle-plugin/'
		}
		maven {
			name = 'AliyunPublic'
			url = 'https://maven.aliyun.com/repository/public/'
		}
		maven {
			name = 'FabricMirror'
			url = 'https://repository.hanbings.io/proxy/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'mchjong'
include 'engine', 'fabric', 'forge', 'art'
