pluginManagement {
	repositories {
		maven {
			name = 'AliyunGradlePlugin'
			url = 'https://maven.aliyun.com/repository/gradle-plugin/'
		}
		maven {
			name = 'AliyunPublic'
			url = 'https://maven.aliyun.com/repository/public/'
		}
		maven {
			name = 'FabricMirror'
			url = 'https://repository.hanbings.io/proxy/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'mchjong'
include 'engine', 'fabric', 'neoforge', 'art'
