modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"

[[mods]]
modId="mchjong"
version="${version}"
displayName="MChjong"
logoFile="assets/mchjong/icon.png"
authors="SkyEye_FAST"
description='''A seated, in-world riichi mahjong table for three or four players.'''

[[mixins]]
config="mchjong.client.mixins.json"

[[dependencies.mchjong]]
modId="neoforge"
type="required"
versionRange="[${neo_loader_min_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.mchjong]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.mchjong]]
modId="ponder"
type="optional"
versionRange="[${ponder_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.mchjong]]
modId="jei"
type="optional"
versionRange="[${jei_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.mchjong]]
modId="emi"
type="optional"
versionRange="[${emi_version},)"
ordering="AFTER"
side="CLIENT"
