modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"

[[mods]]
modId="mchjong"
version="${version}"
displayName="MChjong"
logoFile="assets/mchjong/icon.png"
authors="SkyEye_FAST"
description='''Playable, in-world mahjong tables with configurable rules.'''

[[mixins]]
config="mchjong.client.mixins.json"

[[mixins]]
config="mchjong.create.mixins.json"

[[dependencies.mchjong]]
modId="neoforge"
type="required"
versionRange="[${neo_loader_min_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.mchjong]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.mchjong]]
modId="ponder"
type="optional"
versionRange="[${create_ponder_min_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.mchjong]]
modId="patchouli"
type="optional"
versionRange="[${patchouli_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.mchjong]]
modId="create"
type="optional"
versionRange="[${create_version},6.1)"
ordering="AFTER"
side="BOTH"

[[dependencies.mchjong]]
modId="touhou_little_maid"
type="optional"
versionRange="[${touhou_little_maid_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.mchjong]]
modId="jei"
type="optional"
versionRange="[${jei_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.mchjong]]
modId="emi"
type="optional"
versionRange="[${emi_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.mchjong]]
modId="roughlyenoughitems"
type="optional"
versionRange="[${rei_version},)"
ordering="AFTER"
side="CLIENT"
